
[project]
name = "raphael-ai"
version = "0.6.0"
description = "Raphael — Doctor's Copilot (prototype stack)"
requires-python = ">=3.9"
dependencies = [
  "fastapi>=0.115.0",
  "uvicorn[standard]>=0.30.0",
  "pydantic>=2.8.0",
  "python-multipart>=0.0.9",
  "requests>=2.32.0",
]

[tool.uvicorn]
host = "0.0.0.0"
port = 10000
reload = false
